name: yb_ride
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # for changing app icon
  icons_launcher: ^2.1.7
  # for app fonts
  google_fonts: ^6.1.0
  # for state management
  get: ^4.6.6
  # for initializing firebase
  firebase_core: ^2.24.2
  # for authentication
  firebase_auth: ^4.16.0
  # for  firebase firestore database
  cloud_firestore: ^4.14.0
  # for firebase storage
  firebase_storage: ^11.6.0
  # google sihn in
  google_sign_in: ^6.2.1
  #  for google maps
  google_maps_flutter: ^2.5.3

  #  extra icons
  ionicons: ^0.2.2
#icons
  font_awesome_flutter:
# bottom navigation bar
  persistent_bottom_nav_bar:

# shared prefrences
  shared_preferences:
# country code picker
  fl_country_code_picker:
# internet connectivity
  http: ^1.2.0

#   to get the id of mobile device
  uuid: ^4.3.3
# for date and time
  intl:
  flutter_datetime_picker: ^1.5.1


#  to convert place into latLang
  geocoding: ^2.1.1

  app_settings: ^5.1.1

#    credit card
  flutter_credit_card: ^4.0.1


#  date picker
  syncfusion_flutter_datepicker: ^24.1.47


  # for launching urls
  url_launcher: ^6.2.4
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  connectivity_plus: ^5.0.2
  ikchatbot:
  lottie:
  credit_card_type_detector: ^3.0.0
  credit_card_validator: ^2.1.0

#  for payments
  flutter_stripe:
#  for generting random string
  random_string: ^2.3.1


  card_swiper:
  firebase_messaging:
  flutter_local_notifications:
  flutter_quill: ^9.2.11
#  sharing to social media
  share_plus: ^7.2.2
#  for screenshot the recepit
  screenshot: ^2.1.0
  image_gallery_saver: ^2.0.3




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
    - assets/images/
    - assets/icons/
    - assets/whiteIcons/
    - assets/appImages/
    - assets/carImages/
    - themes/
