name: yb_ride
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # for changing app icon
  icons_launcher: ^2.1.7
  # for app fonts
  google_fonts: ^6.1.0
  # for state management
  get: ^4.6.6
  # for initializing firebase
  firebase_core: ^2.24.2
  # for authentication
  firebase_auth: ^4.16.0
  # for  firebase firestore database
  cloud_firestore: ^4.14.0
  # for firebase storage
  firebase_storage: ^11.6.0
  # google sihn in
  google_sign_in: ^6.2.1
  #  for google maps
  google_maps_flutter: ^2.5.3

  #  extra icons
  ionicons: ^0.2.2

  font_awesome_flutter:

  persistent_bottom_nav_bar:


  shared_preferences:

  fl_country_code_picker:

  app_settings: ^5.1.1

  # for launching urls
  url_launcher: ^6.2.4



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

